# ============= docker-compose.yml =============
version: '3.8'

services:
  # Redis para Cache
  redis:
    image: redis:7-alpine
    container_name: gastos-casa-redis
    restart: unless-stopped
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - gastos-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Aplicación Next.js
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gastos-casa-app
    restart: unless-stopped
    environment:
      # Database SQLite (archivo local)
      DATABASE_URL: file:./prisma/dev.db
      
      # Redis Cache
      REDIS_URL: redis://redis:6379
      REDIS_HOST: redis
      REDIS_PORT: 6379
      
      # Next.js
      NODE_ENV: production
      NEXTAUTH_URL: http://${HOST_IP:-localhost}:3000
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET:-your-super-secret-key-change-this}
      
      # App específicas
      APP_NAME: "Gastos Casa"
      APP_VERSION: "1.0.0"
      
    ports:
      - "3000:3000"
    volumes:
      - ./uploads:/app/uploads
      - ./backups:/app/backups
      - ./prisma:/app/prisma  # Montar SQLite database
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - gastos-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000/api/health", "||", "exit", "1"]
      interval: 30s
      timeout: 10s
      retries: 3


volumes:
  redis_data:
    driver: local

networks:
  gastos-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16